//! Oracle-backed differential test suite for PRF-001, POL-001, and POL-002.
//!
//! Verifies that `symbrain-policy` matches the Go oracle's exact outputs for all
//! data-driven language-neutral fixtures generated by `scripts/policy-oracle`.

use serde::Deserialize;
use std::collections::BTreeMap;

use symbrain_policy::policy::ForeignTool;
use symbrain_policy::policy::eval::{evaluate, evaluate_preset};
use symbrain_policy::policy::foreign::evaluate_foreign;
use symbrain_policy::profile::ServerConfig;
use symbrain_policy::profile::parse::parse;

#[derive(Deserialize)]
struct OracleSuite {
    profile_cases: Vec<ProfileCase>,
    policy_cases: Vec<PolicyCase>,
}

#[derive(Deserialize)]
struct ExpectedServer {
    enabled: bool,
    #[serde(default)]
    mode: String,
    #[serde(default)]
    command: String,
    #[serde(default)]
    args: Vec<String>,
    #[serde(default)]
    url: String,
    #[serde(default)]
    access: String,
    #[serde(default)]
    tools_allow: Vec<String>,
    #[serde(default)]
    tools_deny: Vec<String>,
    #[serde(default)]
    tools_read: Vec<String>,
    #[serde(default)]
    tools_write: Vec<String>,
}

#[derive(Deserialize)]
struct ProfileCase {
    id: String,
    input_name: String,
    input_toml: String,
    success: bool,
    #[serde(default)]
    error_substr: String,
    #[serde(default)]
    name: String,
    #[serde(default)]
    description: String,
    #[serde(default)]
    audit: bool,
    #[serde(default)]
    servers: BTreeMap<String, ExpectedServer>,
    #[serde(default)]
    warnings: Vec<String>,
}

#[derive(Deserialize)]
struct ForeignToolInput {
    name: String,
    #[serde(default)]
    read_only_hint: Option<bool>,
}

#[derive(Deserialize)]
struct ToolExposureExpectation {
    class: String,
    source: String,
}

#[derive(Deserialize)]
struct PolicyCase {
    id: String,
    input_server: String,
    input_config: ExpectedServer,
    #[serde(default)]
    input_live_tools: Vec<String>,
    #[serde(default)]
    input_foreign_tools: Vec<ForeignToolInput>,
    #[serde(default)]
    preset_eval: bool,
    #[serde(default)]
    is_foreign: bool,
    success: bool,
    #[serde(default)]
    error_substr: String,
    #[serde(default)]
    exposed: Vec<String>,
    #[serde(default)]
    hidden: Vec<String>,
    #[serde(default)]
    unknown: Vec<String>,
    #[serde(default)]
    exposures: Option<BTreeMap<String, ToolExposureExpectation>>,
}

fn to_server_config(es: &ExpectedServer) -> ServerConfig {
    ServerConfig {
        enabled: es.enabled,
        mode: es.mode.clone(),
        tools_allow: es.tools_allow.clone(),
        tools_deny: es.tools_deny.clone(),
        command: es.command.clone(),
        args: es.args.clone(),
        url: es.url.clone(),
        access: es.access.clone(),
        tools_read: es.tools_read.clone(),
        tools_write: es.tools_write.clone(),
    }
}

fn load_suite() -> OracleSuite {
    let fixture_bytes = include_bytes!("fixtures/oracle_expectations.json");
    serde_json::from_slice(fixture_bytes).expect("parse oracle expectations")
}

fn assert_profile_case(tc: &ProfileCase) {
    let result = parse(&tc.input_name, &tc.input_toml);
    if tc.success {
        let p = result.unwrap_or_else(|err| panic!("case {}: expected success, got: {err}", tc.id));
        assert_eq!(p.name, tc.name, "case {}: name mismatch", tc.id);
        assert_eq!(
            p.description, tc.description,
            "case {}: description mismatch",
            tc.id
        );
        assert_eq!(
            p.audit.enabled, tc.audit,
            "case {}: audit.enabled mismatch",
            tc.id
        );
        assert_eq!(p.warnings, tc.warnings, "case {}: warnings mismatch", tc.id);

        for (alias, expected) in &tc.servers {
            let actual = p.server(alias);
            assert_eq!(
                actual.enabled, expected.enabled,
                "case {} server {}: enabled mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.mode, expected.mode,
                "case {} server {}: mode mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.command, expected.command,
                "case {} server {}: command mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.args, expected.args,
                "case {} server {}: args mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.url, expected.url,
                "case {} server {}: url mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.access, expected.access,
                "case {} server {}: access mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.tools_allow, expected.tools_allow,
                "case {} server {}: tools_allow mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.tools_deny, expected.tools_deny,
                "case {} server {}: tools_deny mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.tools_read, expected.tools_read,
                "case {} server {}: tools_read mismatch",
                tc.id, alias
            );
            assert_eq!(
                actual.tools_write, expected.tools_write,
                "case {} server {}: tools_write mismatch",
                tc.id, alias
            );
        }
    } else {
        let err = result.expect_err(&format!(
            "case {}: expected error, but parsed successfully",
            tc.id
        ));
        let err_str = err.to_string();
        assert!(
            !tc.error_substr.is_empty(),
            "case {}: oracle fixture has empty error_substr",
            tc.id
        );
        assert!(
            err_str.contains(&tc.error_substr),
            "case {}: expected error containing {:?}, got {:?}",
            tc.id,
            tc.error_substr,
            err_str
        );
    }
}

#[test]
fn test_oracle_backed_profile_cases() {
    let suite = load_suite();
    for tc in &suite.profile_cases {
        assert_profile_case(tc);
    }
}

#[test]
fn test_oracle_backed_policy_cases() {
    let suite = load_suite();
    for tc in &suite.policy_cases {
        let cfg = to_server_config(&tc.input_config);
        let result = if tc.preset_eval {
            evaluate_preset(&tc.input_server, &cfg)
        } else if tc.is_foreign || !tc.input_foreign_tools.is_empty() {
            let tools: Vec<ForeignTool> = tc
                .input_foreign_tools
                .iter()
                .map(|ft| {
                    let mut t = ForeignTool::new(&ft.name);
                    if let Some(h) = ft.read_only_hint {
                        t = t.with_read_only_hint(h);
                    }
                    t
                })
                .collect();
            evaluate_foreign(&tc.input_server, &cfg, &tools)
        } else {
            evaluate(&tc.input_server, &cfg, &tc.input_live_tools)
        };

        if tc.success {
            let rep =
                result.unwrap_or_else(|err| panic!("case {}: expected success, got: {err}", tc.id));
            assert_eq!(rep.exposed, tc.exposed, "case {}: exposed mismatch", tc.id);
            assert_eq!(rep.hidden, tc.hidden, "case {}: hidden mismatch", tc.id);
            assert_eq!(rep.unknown, tc.unknown, "case {}: unknown mismatch", tc.id);
            if let Some(expected_exposures) = &tc.exposures {
                let actual_exposures = rep.exposures.expect("expected exposures map");
                for (tool, exp) in expected_exposures {
                    let actual = actual_exposures.get(tool).unwrap_or_else(|| {
                        panic!("case {}: tool {tool} missing from exposures", tc.id)
                    });
                    assert_eq!(
                        actual.class, exp.class,
                        "case {} tool {}: class mismatch",
                        tc.id, tool
                    );
                    assert_eq!(
                        actual.source, exp.source,
                        "case {} tool {}: source mismatch",
                        tc.id, tool
                    );
                }
            }
        } else {
            let err = result.expect_err(&format!("case {}: expected error, got report", tc.id));
            let err_str = err.to_string();
            assert!(
                !tc.error_substr.is_empty(),
                "case {}: oracle fixture has empty error_substr",
                tc.id
            );
            assert!(
                err_str.contains(&tc.error_substr),
                "case {}: expected error containing {:?}, got {:?}",
                tc.id,
                tc.error_substr,
                err_str
            );
        }
    }
}
