// CLI oracle: generates frozen expectations for the symbrain command tree
// and flags from the REAL Go implementation at the pinned revision.
//
// The oracle invokes the production Go binary built from the pinned revision
// (via run-go-oracle.sh) and captures the exact stdout/stderr/exit-code
// behaviour for each command, subcommand, flag, and negative case.
//
// It does NOT re-implement command behaviour or hand-write expected output.
// All expectations are generated by running the real production code.
//
// Usage:
//
//	go run ./scripts/cli-oracle -check          # verify fixture is current
//	go run ./scripts/cli-oracle -output path    # regenerate fixture
//
// The frozen fixture is compared in Rust tests via cli_tree_tests.rs.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"
)

// caseTimeout bounds every case. Cases like `memory serve` start a listener
// instead of exiting; without a bound the oracle blocks forever on any machine
// where the port is free, which is every CI runner. A case that has to be
// killed is a finding, not a pass: it is recorded with a timeout marker so the
// fixture cannot silently encode a hang.
const caseTimeout = 20 * time.Second

// servePort is the port `memory serve` binds. The recorded expectation holds a
// bind-failure transcript, so the oracle pins the port itself before the case
// runs. Otherwise the case's outcome would depend on whether something happens
// to be listening on the machine: free port means the server starts and blocks,
// occupied port means the recorded error. Pinning makes the case deterministic.
const servePort = "127.0.0.1:8787"

// holdServePort binds servePort for the duration of the oracle and returns the
// listener so the caller can close it. A bind failure means something else
// already holds the port, which produces the same transcript the fixture
// records, so that is not an error.
func holdServePort() net.Listener {
	ln, err := net.Listen("tcp", servePort)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cli-oracle: %s already in use; relying on the existing listener\n", servePort)
		return nil
	}
	return ln
}

// TestCase captures one input scenario: args, expected stdout/stderr/exit.
type TestCase struct {
	ID          string   `json:"id"`
	Args        []string `json:"args"`
	ExitCode    int      `json:"exit_code"`
	Stdout      string   `json:"stdout"`
	Stderr      string   `json:"stderr"`
	Description string   `json:"description"`
}

// Suite is a collection of test cases.
type Suite struct {
	Cases []TestCase `json:"cases"`
}

func main() {
	check := flag.Bool("check", false, "fail if generated output does not match existing file")
	output := flag.String("output", "rust/symbrain-cli/tests/fixtures/cli_tree_expectations.json", "output path")
	goBinary := flag.String("go-binary", "", "path to Go binary (defaults to building via run-go-oracle.sh)")
	flag.Parse()

	if err := setupOracleEnv(); err != nil {
		fmt.Fprintf(os.Stderr, "setup isolation root: %v\n", err)
		os.Exit(1)
	}
	defer os.RemoveAll(oracleRoot)

	// Pin the serve port so `memory serve` produces the recorded bind-failure
	// transcript on every machine, instead of starting a server that runs until
	// its case bound kills it.
	if ln := holdServePort(); ln != nil {
		defer ln.Close()
	}

	cases, err := buildCases(*goBinary)
	if err != nil {
		fmt.Fprintf(os.Stderr, "build Go oracle binary: %v\n", err)
		return
	}
	data, err := json.MarshalIndent(cases, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "json marshal: %v\n", err)
		os.Exit(1)
	}
	data = append(data, '\n')

	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", *output, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, data) {
			fmt.Fprintf(os.Stderr, "%s is out of date; run go run ./scripts/cli-oracle -output %s\n", *output, *output)
			os.Exit(1)
		}
		fmt.Printf("PASS: cli oracle deterministic check passed (%d cases)\n", len(cases))
		return
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", filepath.Dir(*output), err)
		os.Exit(1)
	}

	if err := os.WriteFile(*output, data, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *output, err)
		os.Exit(1)
	}

	fmt.Printf("Wrote %s (%d cases)\n", *output, len(cases))
}

// oracleEnv and oracleRoot isolate every case from the ambient machine:
// HOME, XDG roots and (on Windows) the user-profile roots point into a
// throwaway directory, so the oracle cannot read or write the operator's real
// config, profiles or managed binaries. Paths in captured output become <root>.
var (
	oracleEnv  []string
	oracleRoot string
	oracleCwd  string
)

func setupOracleEnv() error {
	root, err := os.MkdirTemp("", "symbrain-cli-oracle.")
	if err != nil {
		return err
	}
	// TMPDIR sits under a symlinked ancestor on macOS (/var -> private/var) and
	// on some Linux setups (/tmp -> ...). A symlinked ancestor changes the
	// `sync` case's outcome (see #630), so the root is resolved to its real
	// path before anything is built on top of it.
	if resolved, err := filepath.EvalSymlinks(root); err == nil {
		root = resolved
	}
	oracleRoot = root
	oracleCwd, _ = os.Getwd()
	home := filepath.Join(root, "home")
	if err := os.MkdirAll(home, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(root, "cwd"), 0o755); err != nil {
		return err
	}
	// PATH is pinned to an empty directory. The `skills targets` INSTALLED
	// column follows harness-CLI detection over PATH, so inheriting the
	// operator's PATH froze the recorder's machine into the fixture: the same
	// command reported claude/codex/antigravity/hermes as INSTALLED true on a
	// developer machine and false on a CI runner. An empty PATH makes the
	// column report false everywhere, which is the machine-independent truth
	// for an isolated root.
	emptyPath := filepath.Join(root, "empty-path")
	if err := os.MkdirAll(emptyPath, 0o755); err != nil {
		return err
	}

	oracleEnv = os.Environ()
	for _, pair := range [][2]string{
		{"HOME", home},
		{"XDG_CONFIG_HOME", filepath.Join(home, ".config")},
		{"XDG_DATA_HOME", filepath.Join(root, "data")},
		{"XDG_CACHE_HOME", filepath.Join(root, "cache")},
		{"XDG_STATE_HOME", filepath.Join(root, "state")},
		{"PATH", emptyPath},
	} {
		oracleEnv = setEnv(oracleEnv, pair[0], pair[1])
	}
	if runtime.GOOS == "windows" {
		appData := filepath.Join(home, "AppData", "Roaming")
		localAppData := filepath.Join(home, "AppData", "Local")
		temp := filepath.Join(root, "temp")
		for _, path := range []string{appData, localAppData, temp} {
			if err := os.MkdirAll(path, 0o755); err != nil {
				return err
			}
		}
		for _, pair := range [][2]string{
			{"USERPROFILE", home},
			{"APPDATA", appData},
			{"LOCALAPPDATA", localAppData},
			{"TEMP", temp},
			{"TMP", temp},
		} {
			oracleEnv = setEnv(oracleEnv, pair[0], pair[1])
		}
		if drive := filepath.VolumeName(home); drive != "" {
			oracleEnv = setEnv(oracleEnv, "HOMEDRIVE", drive)
			oracleEnv = setEnv(oracleEnv, "HOMEPATH", strings.TrimPrefix(home, drive))
		}
	}
	return nil
}

// setEnv replaces an inherited variable instead of appending a duplicate.
// Windows environment variable names are case-insensitive, and leaving both
// runner and oracle values in Cmd.Env can make the selected home ambiguous.
func setEnv(env []string, key, value string) []string {
	filtered := make([]string, 0, len(env)+1)
	for _, entry := range env {
		name, _, ok := strings.Cut(entry, "=")
		if !ok || !strings.EqualFold(name, key) {
			filtered = append(filtered, entry)
		}
	}
	return append(filtered, key+"="+value)
}

// buildCases generates test cases by invoking the real Go binary.
func buildCases(goBinary string) ([]TestCase, error) {
	bin := goBinary
	if bin == "" {
		var err error
		bin, err = buildGoBinary()
		if err != nil {
			return nil, err
		}
	}

	cases := []TestCase{}

	// Top-level help
	cases = append(cases, runCase(bin, []string{"--help"}, "top-level --help prints full usage"))
	cases = append(cases, runCase(bin, []string{"-h"}, "top-level -h prints full usage"))
	cases = append(cases, runCase(bin, []string{"help"}, "top-level help prints full usage"))
	cases = append(cases, runCase(bin, []string{}, "no arguments prints usage"))

	// Unknown command
	cases = append(cases, runCase(bin, []string{"bogus"}, "unknown command prints usage to stderr"))

	// version command
	cases = append(cases, runCase(bin, []string{"version"}, "version bare prints human-readable"))
	cases = append(cases, runCase(bin, []string{"version", "--json"}, "version --json prints JSON"))
	cases = append(cases, runCase(bin, []string{"--json", "version"}, "version with --json before command"))
	cases = append(cases, runCase(bin, []string{"version", "--bogus"}, "version rejects unknown flag"))
	cases = append(cases, runCase(bin, []string{"version", "--bogus=123"}, "version rejects unknown flag with value"))
	cases = append(cases, runCase(bin, []string{"version", "-h"}, "version -h prints usage"))
	cases = append(cases, runCase(bin, []string{"version", "-help"}, "version -help prints usage"))
	cases = append(cases, runCase(bin, []string{"version", "--help"}, "version --help prints usage"))
	cases = append(cases, runCase(bin, []string{"version", "extra"}, "version rejects extra positional"))
	cases = append(cases, runCase(bin, []string{"version", "--", "extra"}, "version rejects positional after terminator"))
	cases = append(cases, runCase(bin, []string{"version", "-"}, "version rejects bare hyphen"))

	// config path
	cases = append(cases, runCase(bin, []string{"config", "path"}, "config path prints path"))
	cases = append(cases, runCase(bin, []string{"config", "path", "extra"}, "config path rejects extra arg"))
	cases = append(cases, runCase(bin, []string{"config", "path", "--unexpected"}, "config path rejects unknown flag"))

	// config get (without key - prints whole file or error)
	cases = append(cases, runCase(bin, []string{"config", "get"}, "config get prints whole file"))
	cases = append(cases, runCase(bin, []string{"config", "get", "nonexistent.key"}, "config get missing key"))

	// config set (without args)
	cases = append(cases, runCase(bin, []string{"config", "set"}, "config set missing args"))

	// profile subcommands
	cases = append(cases, runCase(bin, []string{"profile", "list"}, "profile list"))
	cases = append(cases, runCase(bin, []string{"profile", "show"}, "profile show missing name"))
	cases = append(cases, runCase(bin, []string{"profile", "add"}, "profile add missing name"))
	cases = append(cases, runCase(bin, []string{"profile", "remove"}, "profile remove missing name"))

	// doctor flags
	cases = append(cases, runCase(bin, []string{"doctor", "--unknown"}, "doctor rejects unknown flag"))
	cases = append(cases, runCase(bin, []string{"doctor", "--vault-agent"}, "doctor missing vault-agent value"))

	// init
	cases = append(cases, runCase(bin, []string{"init"}, "init"))
	cases = append(cases, runCase(bin, []string{"init", "--help"}, "init --help prints usage"))

	// setup
	cases = append(cases, runCase(bin, []string{"setup", "--unknown"}, "setup rejects unknown flag"))

	// install
	cases = append(cases, runCase(bin, []string{"install"}, "install missing harness"))
	cases = append(cases, runCase(bin, []string{"install", "--dry-run"}, "install missing harness with dry-run"))
	cases = append(cases, runCase(bin, []string{"install", "--unknown"}, "install rejects unknown flag"))

	// uninstall
	cases = append(cases, runCase(bin, []string{"uninstall"}, "uninstall"))
	cases = append(cases, runCase(bin, []string{"uninstall", "--unknown"}, "uninstall rejects unknown flag"))

	// sync
	cases = append(cases, runCase(bin, []string{"sync"}, "sync"))
	cases = append(cases, runCase(bin, []string{"sync", "--unknown"}, "sync rejects unknown flag"))

	// harness
	cases = append(cases, runCase(bin, []string{"harness"}, "harness missing subcommand"))
	cases = append(cases, runCase(bin, []string{"harness", "list"}, "harness list"))
	cases = append(cases, runCase(bin, []string{"harness", "health"}, "harness health"))

	// usage
	cases = append(cases, runCase(bin, []string{"usage"}, "usage"))

	// mcp
	cases = append(cases, runCase(bin, []string{"mcp"}, "mcp missing flags"))
	cases = append(cases, runCase(bin, []string{"mcp", "--unknown"}, "mcp rejects unknown flag"))

	// audit
	cases = append(cases, runCase(bin, []string{"audit"}, "audit"))
	cases = append(cases, runCase(bin, []string{"audit", "--unknown"}, "audit rejects unknown flag"))

	// skills
	cases = append(cases, runCase(bin, []string{"skills"}, "skills"))
	cases = append(cases, runCase(bin, []string{"skills", "list"}, "skills list"))
	cases = append(cases, runCase(bin, []string{"skills", "status"}, "skills status"))
	cases = append(cases, runCase(bin, []string{"skills", "targets"}, "skills targets"))
	cases = append(cases, runCase(bin, []string{"skills", "log"}, "skills log"))
	cases = append(cases, runCase(bin, []string{"skills", "sync"}, "skills sync"))
	cases = append(cases, runCase(bin, []string{"skills", "doctor"}, "skills doctor"))
	cases = append(cases, runCase(bin, []string{"skills", "unknown"}, "skills unknown subcommand"))
	cases = append(cases, runCase(bin, []string{"skills", "list", "--unknown"}, "skills list rejects unknown flag"))

	// activity
	cases = append(cases, runCase(bin, []string{"activity"}, "activity"))
	cases = append(cases, runCase(bin, []string{"activity", "search"}, "activity search missing args"))
	cases = append(cases, runCase(bin, []string{"activity", "unknown"}, "activity unknown subcommand"))

	// memory
	cases = append(cases, runCase(bin, []string{"memory"}, "memory"))
	cases = append(cases, runCase(bin, []string{"memory", "list"}, "memory list"))
	cases = append(cases, runCase(bin, []string{"memory", "search"}, "memory search missing query"))
	cases = append(cases, runCase(bin, []string{"memory", "set"}, "memory set missing content"))
	cases = append(cases, runCase(bin, []string{"memory", "delete"}, "memory delete missing id"))
	cases = append(cases, runCase(bin, []string{"memory", "rules"}, "memory rules"))
	cases = append(cases, runCase(bin, []string{"memory", "query-log"}, "memory query-log"))
	cases = append(cases, runCase(bin, []string{"memory", "sync"}, "memory sync missing --remote"))
	cases = append(cases, runCase(bin, []string{"memory", "serve"}, "memory serve"))

	// guard
	cases = append(cases, runCase(bin, []string{"guard"}, "guard missing subcommand"))
	cases = append(cases, runCase(bin, []string{"guard", "version"}, "guard version"))
	cases = append(cases, runCase(bin, []string{"guard", "doctor"}, "guard doctor, exit 1 (issues found)"))
	cases = append(cases, runCase(bin, []string{"guard", "decide"}, "guard decide (reads stdin)"))
	cases = append(cases, runCase(bin, []string{"guard", "grants"}, "guard grants"))
	cases = append(cases, runCase(bin, []string{"guard", "scan"}, "guard scan"))
	cases = append(cases, runCase(bin, []string{"guard", "unknown"}, "guard unknown subcommand"))

	// vault (passthrough to symvault)
	cases = append(cases, runCase(bin, []string{"vault"}, "vault missing subcommand"))

	// subcommand help
	cases = append(cases, runCase(bin, []string{"skills", "list", "--help"}, "skills list --help prints usage"))
	cases = append(cases, runCase(bin, []string{"memory", "list", "--help"}, "memory list --help"))
	cases = append(cases, runCase(bin, []string{"guard", "decide", "--help"}, "guard decide --help"))

	// serve deprecated alias
	cases = append(cases, runCase(bin, []string{"serve"}, "serve prints deprecation warning to stderr"))

	// Global --json flag with version
	cases = append(cases, runCase(bin, []string{"--json", "version"}, "version with global --json flag"))

	// Unknown flag at top level (treated as unknown command by run())
	cases = append(cases, runCase(bin, []string{"--unknown"}, "top-level unknown flag treated as unknown command"))

	return cases, nil
}

// runCase invokes the Go binary with args and captures stdout/stderr/exit.
// The case is bounded by caseTimeout: a command that does not exit on its own
// is killed and marked, so a hanging case can never stall the oracle.
func runCase(binary string, args []string, description string) TestCase {
	ctx, cancel := context.WithTimeout(context.Background(), caseTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, binary, args...)
	cmd.Env = oracleEnv
	// Every case runs in a scratch directory: commands like `sync` write
	// managed blocks into the project's instruction files, and an oracle must
	// never mutate the checkout it is measuring.
	cmd.Dir = filepath.Join(oracleRoot, "cwd")
	cmd.WaitDelay = 2 * time.Second
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()

	// A case killed by the bound is reported as such instead of being folded
	// into a generic failure: the fixture must not encode "it hung" as an
	// ordinary exit code.
	if ctx.Err() == context.DeadlineExceeded {
		fmt.Fprintf(os.Stderr, "cli-oracle: case %q exceeded %s and was killed\n",
			strings.Join(args, " "), caseTimeout)
		return TestCase{
			ID:          strings.Join(append([]string{"go"}, args...), " "),
			Args:        args,
			ExitCode:    -1,
			Stdout:      stdout.String(),
			Stderr:      stderr.String() + "\n<timeout: case exceeded " + caseTimeout.String() + ">",
			Description: description,
		}
	}

	exitCode := 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			exitCode = 1
		}
	}

	// Normalize both streams: the isolated root is per-invocation, and the
	// toolchain lines are environment-dependent.
	stdoutStr := normalizeStdout(stdout.String(), oracleRoot)
	stderrStr := normalizeStderr(normalizeStdout(stderr.String(), oracleRoot))

	return TestCase{
		ID:          strings.Join(append([]string{"go"}, args...), " "),
		Args:        args,
		ExitCode:    exitCode,
		Stdout:      stdoutStr,
		Stderr:      stderrStr,
		Description: description,
	}
}

// normalizeStdout rewrites the per-invocation isolation root. macOS reports
// the same directory both as /var/... and as /private/var/..., so both forms
// have to be rewritten or the fixture drifts between runs.
var (
	toolchainLine     = regexp.MustCompile(`(?m)^(\s*go\s+)go\d+\.\d+(?:\.\d+)?$`)
	platformLine      = regexp.MustCompile(`(?m)^(\s*os/arch\s+)\S+$`)
	claudeDesktopPath = regexp.MustCompile(`Library/Application Support/Claude|\.config/[Cc]laude`)
	// `guard doctor`'s own header block uses a different shape than `version`'s
	// ("  Go:        go1.26.7" / "  OS/Arch:   darwin/arm64", capitalized
	// labels with colons) that toolchainLine/platformLine above don't match,
	// so this case's "Go:" line silently pinned to whatever toolchain built
	// the reference binary at recording time instead of being a true accepted
	// difference — caught when a regeneration built with a different local Go
	// toolchain than the pinned one produced an unrelated-looking diff.
	doctorToolchainLine = regexp.MustCompile(`(?m)^(\s*Go:\s+)\S+$`)
	doctorOsArchLine    = regexp.MustCompile(`(?m)^(\s*OS/Arch:\s+)\S+$`)
)

func normalizeStdout(s, root string) string {
	if root == "" {
		return s
	}
	s = strings.ReplaceAll(s, "/private"+root, "<root>")
	s = strings.ReplaceAll(s, root, "<root>")
	// Cases that report project-scoped paths embed the checkout location, which
	// differs per machine and per CI runner.
	if oracleCwd != "" && oracleCwd != root {
		s = strings.ReplaceAll(s, "/private"+oracleCwd, "<repo>")
		s = strings.ReplaceAll(s, oracleCwd, "<repo>")
	}
	// `version` prints the building toolchain and the host platform. Those are
	// accepted differences rather than verified matches: no fixture can pin
	// them and stay portable across runners.
	s = toolchainLine.ReplaceAllString(s, "${1}<go>")
	s = platformLine.ReplaceAllString(s, "${1}<os/arch>")
	s = doctorToolchainLine.ReplaceAllString(s, "${1}<go>")
	s = doctorOsArchLine.ReplaceAllString(s, "${1}<os/arch>")
	// Claude Desktop's config directory: internal/harness resolves
	// "Library/Application Support/Claude" on macOS but a different,
	// platform-correct XDG fallback on Linux ("~/.config/Claude" for harness
	// discovery, "~/.config/claude" lowercase for corekit's mcpcfgkit used by
	// guard scan) — both correct for their package, neither pinnable in a
	// fixture recorded on one machine. Mirrors the same fix already applied
	// to the Rust consumer test (cli_tree_tests.rs) for the identical reason.
	return claudeDesktopPath.ReplaceAllString(s, "<claude-desktop-dir>")
}

// normalizeStderr removes toolchain identifiers and absolute paths from
// stderr output so the fixture is stable across environments.
func normalizeStderr(s string) string {
	// Remove toolchain lines
	s = removeLinePrefix(s, "Go:")
	s = removeLinePrefix(s, "go ")
	// Remove absolute paths in error messages
	// (the oracle runs in an isolated worktree, so paths are predictable)
	return s
}

func removeLinePrefix(s, prefix string) string {
	lines := strings.Split(s, "\n")
	var out []string
	for _, line := range lines {
		if !strings.HasPrefix(line, prefix) {
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}

// executableName returns the native executable name for a Go binary.
func executableName(name, goos string) string {
	if goos == "windows" && !strings.HasSuffix(strings.ToLower(name), ".exe") {
		return name + ".exe"
	}
	return name
}

// buildGoBinary builds the Go binary in the oracle's isolated temp root.
// An explicit -go-binary remains available to callers that need a pinned build.
func buildGoBinary() (string, error) {
	bin := filepath.Join(oracleRoot, executableName("symbrain-go", runtime.GOOS))
	cmd := exec.Command("go", "build", "-o", bin, "./cmd/symbrain")
	cmd.Dir = oracleCwd
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
	if output, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("go build: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return bin, nil
}
