package syncclient

import (
	"context"
	"errors"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"

	"github.com/danieljustus/symaira-brain/internal/memory/config"
	"github.com/danieljustus/symaira-brain/internal/memory/db"
)

// httpsOnlyServer is a tiny TLS test server used to verify that the
// transport is actually upgraded when the user supplies a valid https URL.
// The certificate is generated by httptest; we never reach the listener in
// these tests — they only confirm that URL acceptance and Client
// construction succeed for https and reject for everything else.
func httpsOnlyServer(t *testing.T) *httptest.Server {
	t.Helper()
	ts := httptest.NewTLSServer(nil)
	t.Cleanup(ts.Close)
	return ts
}

func TestValidateRemoteURL(t *testing.T) {
	tests := []struct {
		name         string
		url          string
		allowInsec   bool
		wantErr      bool
		wantContains string
	}{
		{name: "https accepted", url: "https://example.com", allowInsec: false, wantErr: false},
		{name: "https with port and path", url: "https://example.com:8443/api", allowInsec: false, wantErr: false},
		{name: "https uppercase scheme", url: "HTTPS://example.com", allowInsec: false, wantErr: false},
		{name: "http loopback host allowed", url: "http://localhost:8080", allowInsec: false, wantErr: false},
		{name: "http loopback IP allowed", url: "http://127.0.0.1:8080", allowInsec: false, wantErr: false},
		{name: "http loopback IPv6 allowed", url: "http://[::1]:8080", allowInsec: false, wantErr: false},
		{name: "http non-loopback rejected", url: "http://example.com", allowInsec: false, wantErr: true, wantContains: "https"},
		{name: "http non-loopback with override", url: "http://example.com", allowInsec: true, wantErr: false},
		{name: "http non-loopback with port rejected", url: "http://10.0.0.5:8080", allowInsec: false, wantErr: true, wantContains: "https"},
		{name: "ftp rejected", url: "ftp://example.com", allowInsec: false, wantErr: true, wantContains: "scheme"},
		{name: "scheme-less rejected", url: "example.com", allowInsec: false, wantErr: true, wantContains: "scheme"},
		{name: "empty rejected", url: "", allowInsec: false, wantErr: true, wantContains: "required"},
		{name: "http empty host rejected", url: "http://", allowInsec: true, wantErr: true, wantContains: "host"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateRemoteURL(tt.url, tt.allowInsec)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("ValidateRemoteURL(%q) = nil, want error", tt.url)
				}
				if tt.wantContains != "" && !strings.Contains(err.Error(), tt.wantContains) {
					t.Errorf("error %q does not contain %q", err, tt.wantContains)
				}
				return
			}
			if err != nil {
				t.Fatalf("ValidateRemoteURL(%q) = %v, want nil", tt.url, err)
			}
		})
	}
}

func TestErrInsecureRemote_IsExported(t *testing.T) {
	if ErrInsecureRemote == nil {
		t.Fatal("ErrInsecureRemote must be a non-nil sentinel")
	}
	if !strings.Contains(ErrInsecureRemote.Error(), "https") {
		t.Errorf("ErrInsecureRemote text %q must mention https", ErrInsecureRemote)
	}
}

func TestNewClient_RejectsInsecureRemote(t *testing.T) {
	_, err := NewClient("http://example.com", "token", nil)
	if err == nil {
		t.Fatal("NewClient must reject non-loopback http URL")
	}
	if !errors.Is(err, ErrInsecureRemote) {
		t.Errorf("error %v is not ErrInsecureRemote", err)
	}
}

func TestNewClient_AcceptsLoopback(t *testing.T) {
	c, err := NewClient("http://127.0.0.1:1", "token", nil)
	if err != nil {
		t.Fatalf("NewClient loopback: %v", err)
	}
	if c == nil {
		t.Fatal("NewClient returned nil")
	}
}

func TestNewClientWithOptions_OverridePermitsInsecure(t *testing.T) {
	c, err := NewClientWithOptions("http://example.com", "token", nil, true)
	if err != nil {
		t.Fatalf("NewClientWithOptions with override: %v", err)
	}
	if c == nil {
		t.Fatal("NewClientWithOptions returned nil")
	}
}

func TestNewClient_AcceptsHTTPS(t *testing.T) {
	ts := httpsOnlyServer(t)
	c, err := NewClient(ts.URL, "token", nil)
	if err != nil {
		t.Fatalf("NewClient https: %v", err)
	}
	if c == nil {
		t.Fatal("NewClient returned nil for https server")
	}
}

// TestRun_RejectsInsecureRemoteURL covers the security guard inside Run:
// the URL must be validated before any DB or network work happens, so a
// non-loopback http remote must fail without touching the database.
func TestRun_RejectsInsecureRemoteURL(t *testing.T) {
	t.Setenv("JWT_SECRET_KEY", "url-guard-test-secret")

	// A local DB still exists, but Run must not open it; we expect the
	// URL guard to fire first.
	cfg := config.Defaults()
	cfg.Database.Path = filepath.Join(t.TempDir(), "local.db")
	database, err := db.Open(cfg)
	if err != nil {
		t.Fatalf("open local db: %v", err)
	}
	t.Cleanup(func() { _ = database.Close() })

	_, err = Run(context.Background(), Options{
		Remote: "http://example.com",
		Token:  "t", Pull: true, DB: database,
	})
	if err == nil {
		t.Fatal("Run must reject non-loopback http remote")
	}
	if !errors.Is(err, ErrInsecureRemote) {
		t.Errorf("Run error %v is not ErrInsecureRemote", err)
	}
}

func TestRun_AllowInsecureHTTPOverride(t *testing.T) {
	t.Setenv("JWT_SECRET_KEY", "url-guard-override-secret")
	// We never reach the network: validate just allows the URL, the
	// subsequent connection fails with a transport error. That confirms
	// the override gate is the only thing standing between Run and the
	// request.
	cfg := config.Defaults()
	cfg.Database.Path = filepath.Join(t.TempDir(), "local.db")
	database, err := db.Open(cfg)
	if err != nil {
		t.Fatalf("open local db: %v", err)
	}
	t.Cleanup(func() { _ = database.Close() })

	_, err = Run(context.Background(), Options{
		Remote: "http://127.0.0.1:1", // loopback, so no override needed
		Token:  "t", Pull: true, DB: database,
		AllowInsecureHTTP: false,
	})
	// Loopback is allowed without the override: the run will fail at the
	// transport step (nothing listens on 127.0.0.1:1) but the URL guard
	// must not be the cause.
	if err != nil && errors.Is(err, ErrInsecureRemote) {
		t.Fatalf("loopback http must not trip ErrInsecureRemote: %v", err)
	}
}

func TestIsLoopbackHost(t *testing.T) {
	tests := []struct {
		host string
		want bool
	}{
		{"localhost", true},
		{"Localhost", true},
		{"LOCALHOST", true},
		{"127.0.0.1", true},
		{"127.0.0.2", true},
		{"::1", true},
		{"example.com", false},
		{"10.0.0.1", false},
		{"", false},
		{"localhost.example.com", false},
	}
	for _, tt := range tests {
		t.Run(tt.host, func(t *testing.T) {
			if got := isLoopbackHost(tt.host); got != tt.want {
				t.Errorf("isLoopbackHost(%q) = %v, want %v", tt.host, got, tt.want)
			}
		})
	}
}
