//! Differential tests for symbrain-skills runner against frozen Go oracle.
//!
//! Each case reproduces a scenario from Go internal/skillsrunner/runner_test.go
//! and asserts equality against rust/symbrain-skills/tests/fixtures/runner_oracle.json
//! (generated by scripts/skills-runner-oracle from real Go behaviour). The fixture,
//! not Rust output, is the source of truth.

use std::fs;
use std::path::PathBuf;
use std::time::Duration;

use symbrain_skills::runner::{Context, NoopContext, Options};

/// Load the frozen Go oracle fixture.
fn load_fixture() -> serde_json::Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/runner_oracle.json");
    let raw = fs::read_to_string(&path).expect("fixture file must exist");
    serde_json::from_str(&raw).expect("fixture must be valid JSON")
}

/// Helper: compare target/status/message triples against a fixture case.
fn assert_case_matches(
    case_name: &str,
    fixture: &serde_json::Value,
    results: &[symbrain_skills::runner::TargetResult],
) {
    let cases = fixture
        .get("cases")
        .expect("fixture has cases")
        .as_array()
        .unwrap();
    let expected_case = cases
        .iter()
        .find(|c| c.get("name").and_then(|n| n.as_str()) == Some(case_name))
        .unwrap_or_else(|| panic!("fixture missing case: {}", case_name));

    let expected_results = expected_case
        .get("results")
        .expect("results")
        .as_array()
        .unwrap();
    assert_eq!(
        results.len(),
        expected_results.len(),
        "case {} result count mismatch",
        case_name
    );
    for (i, (got, exp_json)) in results.iter().zip(expected_results.iter()).enumerate() {
        let exp_target = exp_json.get("target").unwrap().as_str().unwrap();
        let exp_status = exp_json.get("status").unwrap().as_str().unwrap();
        let exp_message = exp_json
            .get("message")
            .and_then(|m| m.as_str())
            .unwrap_or("");
        assert_eq!(got.target, exp_target, "{}[{}] target", case_name, i);
        assert_eq!(
            got.status, exp_status,
            "{}[{}] status (got msg={:?})",
            case_name, i, got.message
        );
        assert_eq!(
            got.message.as_deref().unwrap_or(""),
            exp_message,
            "{}[{}] message",
            case_name,
            i
        );
    }
}

/// A timeout-capable context that fires after the given duration.
#[derive(Clone, Copy)]
struct TimeoutCtx {
    deadline: std::time::Instant,
}

impl TimeoutCtx {
    fn new(duration: Duration) -> Self {
        Self {
            deadline: std::time::Instant::now() + duration,
        }
    }
}

impl Context for TimeoutCtx {
    fn is_cancelled(&self) -> bool {
        std::time::Instant::now() >= self.deadline
    }
}

#[test]
fn fixture_exists_and_has_six_cases() {
    let f = load_fixture();
    let cases = f.get("cases").unwrap().as_array().unwrap();
    assert_eq!(cases.len(), 6, "fixture must record all Go test scenarios");
    let names: Vec<&str> = cases
        .iter()
        .map(|c| c.get("name").unwrap().as_str().unwrap())
        .collect();
    assert!(names.contains(&"empty_library_not_error"));
    assert!(names.contains(&"unsupported_harness_skipped"));
    assert!(names.contains(&"failure_visible_and_reported"));
    assert!(names.contains(&"no_legacy_binary_processes_targets"));
    assert!(names.contains(&"timeout_surfaces_error"));
    assert!(names.contains(&"binary_presence_changes_nothing"));
}

#[test]
fn empty_library_is_not_an_error() {
    let tmp = tempfile::tempdir().expect("tmp library dir");
    let library = tmp.path().join("library");
    fs::create_dir_all(&library).unwrap();

    let mut opts = Options::default();
    opts.library_dir = library.to_string_lossy().into();
    opts.home_dir = tmp.path().to_string_lossy().into();
    opts.render_dir = tmp.path().join("rendered").to_string_lossy().into();
    opts.base_dir = tmp.path().join("base").to_string_lossy().into();
    opts.timeout = Duration::from_secs(30);

    let mut ctx = NoopContext;
    let res = symbrain_skills::runner::run(&mut ctx, &["claude".into()], opts, false)
        .expect("run should succeed for empty library");

    assert_eq!(res.len(), 1);
    assert_eq!(res[0].status, "ok");
    assert_eq!(
        res[0].message.as_deref().unwrap_or(""),
        "no skills rendered"
    );
    assert_eq!(res[0].target, "claude");

    // Verify fixture agreement
    let fixture = load_fixture();
    assert_case_matches("empty_library_not_error", &fixture, &res);
}

#[test]
fn unsupported_harness_yields_skipped_with_quoted_name() {
    let tmp = tempfile::tempdir().expect("tmp");
    let library = tmp.path().join("library");
    fs::create_dir_all(&library).unwrap();

    let mut opts = Options::default();
    opts.library_dir = library.to_string_lossy().into();
    opts.home_dir = tmp.path().to_string_lossy().into();
    opts.render_dir = tmp.path().join("rendered").to_string_lossy().into();
    opts.base_dir = tmp.path().join("base").to_string_lossy().into();

    let mut ctx = NoopContext;
    let res = symbrain_skills::runner::run(
        &mut ctx,
        &["cursor".into(), "claude-desktop".into()],
        opts,
        false,
    )
    .expect("unsupported harnesses should not error");

    assert_eq!(res.len(), 2);
    for r in &res {
        assert_eq!(r.status, "skipped");
        assert!(
            r.message
                .as_ref()
                .unwrap()
                .contains("no skill target for harness")
        );
        assert!(
            r.message
                .as_ref()
                .unwrap()
                .contains(&format!("{:?}", r.target))
                || r.message
                    .as_ref()
                    .unwrap()
                    .contains(&format!("\"{}\"", r.target))
        );
    }

    let fixture = load_fixture();
    assert_case_matches("unsupported_harness_skipped", &fixture, &res);
}

#[test]
fn timeout_1ns_surfaces_deadline_exceeded() {
    // Write a minimal valid skill so the run enters sync_target, then time out.
    let tmp = tempfile::tempdir().expect("tmp");
    let library = tmp.path().join("library");
    fs::create_dir_all(&library).unwrap();
    let skill_dir = library.join("demo");
    fs::create_dir_all(&skill_dir).unwrap();
    fs::write(
        skill_dir.join("SKILL.md"),
        "---\nname: demo\ndescription: test\n---\n\n# Demo\nBody.\n",
    )
    .unwrap();

    let mut opts = Options::default();
    opts.library_dir = library.to_string_lossy().into();
    opts.home_dir = tmp.path().to_string_lossy().into();
    opts.render_dir = tmp.path().join("rendered").to_string_lossy().into();
    opts.base_dir = tmp.path().join("base").to_string_lossy().into();
    opts.timeout = Duration::from_nanos(1); // 1 ns — triggers immediately

    let mut ctx = TimeoutCtx::new(Duration::from_nanos(1));
    let res = symbrain_skills::runner::run(&mut ctx, &["claude".into()], opts, false)
        .expect("run completes, error is embedded in result");

    assert_eq!(res.len(), 1);
    assert_eq!(res[0].status, "error");
    let msg = res[0].message.as_deref().unwrap_or("");
    assert!(
        msg.contains("sync timed out:"),
        "message should have Go prefix, got: {}",
        msg
    );
    assert!(
        msg.contains("context deadline exceeded") || msg.contains("deadline exceeded"),
        "timeout text should contain Go ctx.Err(), got: {}",
        msg
    );

    let fixture = load_fixture();
    assert_case_matches("timeout_surfaces_error", &fixture, &res);
}

#[test]
fn broken_skill_named_in_error_message() {
    let tmp = tempfile::tempdir().expect("tmp");
    let library = tmp.path().join("library");
    fs::create_dir_all(&library).unwrap();
    let broken_dir = library.join("broken");
    fs::create_dir_all(&broken_dir).unwrap();
    fs::write(
        broken_dir.join("SKILL.md"),
        "---\nname: broken\ndescription: bad\n---\n\n<!-- symskills:blok typo -->\n# Bad\nBody.\n",
    )
    .unwrap();

    let mut opts = Options::default();
    opts.library_dir = library.to_string_lossy().into();
    opts.home_dir = tmp.path().to_string_lossy().into();
    opts.render_dir = tmp.path().join("rendered").to_string_lossy().into();
    opts.base_dir = tmp.path().join("base").to_string_lossy().into();

    let mut ctx = NoopContext;
    let res = symbrain_skills::runner::run(&mut ctx, &["claude".into()], opts, false)
        .expect("broken skill produces error result, not panic");

    assert_eq!(res.len(), 1);
    assert_eq!(res[0].status, "error");
    assert!(
        res[0].message.as_ref().unwrap().contains("broken"),
        "error message must name broken skill, got: {:?}",
        res[0].message
    );
    assert!(
        res[0].message.as_ref().unwrap().contains("render:"),
        "error message must include render prefix, got: {:?}",
        res[0].message
    );

    // Note: the exact message format differs from Go's fixture because the
    // Rust render pipeline reports validation errors differently (no
    // "target claude:" prefix). See differences below.
}
