//! Environment-sensitive differential tests for the `symbrain-skills` runner.
//!
//! Two Go behaviours can only be reproduced with a controlled environment: the
//! default directory resolution (`HOME`, `XDG_DATA_HOME`) and the fact that a
//! legacy `symskills` binary on `PATH` changes nothing. This crate denies
//! `unsafe_code`, so a test may not mutate its own environment; each scenario
//! therefore runs in a child process whose environment the parent builds with
//! `Command::env`. The child cases are `#[ignore]`d — they only make sense with
//! the environment their parent prepares.
//!
//! Both expectations come from `tests/fixtures/runner_oracle.json`, generated by
//! `scripts/skills-runner-oracle` from the real Go implementation, with the
//! temporary root replaced by the literal `$ROOT`.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

/// Load the frozen Go oracle fixture.
fn load_fixture() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/runner_oracle.json");
    let raw = fs::read_to_string(&path).expect("fixture file must exist");
    serde_json::from_str(&raw).expect("fixture must be valid JSON")
}

/// Runs one `#[ignore]`d child case with a controlled environment and returns
/// its stdout.
fn run_child_case(test_name: &str, envs: &[(String, String)]) -> String {
    let exe = std::env::current_exe().expect("current test executable");
    let mut cmd = Command::new(exe);
    cmd.args(["--exact", test_name, "--ignored", "--nocapture"]);
    // Start from a clean slate: a leaked XDG_DATA_HOME from the developer's
    // shell would silently invalidate every scenario below.
    cmd.env_remove("XDG_DATA_HOME");
    for (key, value) in envs {
        cmd.env(key, value);
    }
    let output = cmd.output().expect("child test process must start");
    assert!(
        output.status.success(),
        "child case {test_name} failed: {}\n{}",
        String::from_utf8_lossy(&output.stderr),
        String::from_utf8_lossy(&output.stdout)
    );
    String::from_utf8_lossy(&output.stdout).into_owned()
}

/// Runs the real runner over a throwaway root and compares the symlink each
/// installed skill ends up as against the frozen Go layout.
///
/// This is the Slice B gate: Go links `.claude/skills/<name>` at
/// `<RenderDir>/<target>/<name>` (`install_ops.go` calls
/// `os.Symlink(item.Path, tmp)` with the path `RenderAll` produced), while the
/// Rust install layer materializes into a per-user cache and links there. The
/// fixture records the Go target under `$ROOT`, so the assertion below fails
/// until the install layer is given the render path.
#[test]
fn installed_symlinks_match_the_frozen_go_layout() {
    let fixture = load_fixture();
    let disk = fixture
        .get("disk")
        .expect("fixture has the on-disk layout")
        .as_array()
        .unwrap();

    let expected: Vec<(String, String)> = disk
        .iter()
        .filter(|entry| entry.get("type").and_then(Value::as_str) == Some("symlink"))
        .map(|entry| {
            (
                entry
                    .get("path")
                    .and_then(Value::as_str)
                    .expect("symlink path")
                    .to_owned(),
                entry
                    .get("target")
                    .and_then(Value::as_str)
                    .expect("symlink target")
                    .to_owned(),
            )
        })
        .collect();
    assert_eq!(expected.len(), 4, "one link per installed harness target");

    let tmp = tempfile::tempdir().expect("runner root");
    let root = tmp.path();
    let library = root.join("library");
    let skill_dir = library.join("demo");
    fs::create_dir_all(&skill_dir).unwrap();
    fs::write(
        skill_dir.join("SKILL.md"),
        "---\nname: demo\ndescription: test\n---\n\n# Demo\nBody.\n",
    )
    .unwrap();

    let opts = symbrain_skills::runner::Options {
        library_dir: library.to_string_lossy().into(),
        render_dir: root.join("rendered").to_string_lossy().into(),
        base_dir: root.join("base").to_string_lossy().into(),
        home_dir: root.to_string_lossy().into(),
        ..symbrain_skills::runner::Options::default()
    };
    let mut ctx = symbrain_skills::runner::NoopContext;
    symbrain_skills::runner::run(
        &mut ctx,
        &[
            "claude".into(),
            "codex".into(),
            "hermes".into(),
            "opencode".into(),
        ],
        opts,
        false,
    )
    .expect("run must succeed over a populated library");

    let root_text = root.to_string_lossy().into_owned();
    // The generator records paths relative to its temp root and targets with
    // that root spelled as $ROOT, so resolve both against this run's root.
    let resolve = |recorded: &str| -> PathBuf {
        if recorded.contains("$ROOT") {
            PathBuf::from(recorded.replacen("$ROOT", &root_text, 1))
        } else {
            root.join(recorded)
        }
    };
    for (recorded_path, recorded_target) in expected {
        let path = resolve(&recorded_path);
        let want_target = resolve(&recorded_target);
        let metadata = fs::symlink_metadata(&path)
            .unwrap_or_else(|error| panic!("{} is not installed: {error}", path.display()));
        assert!(
            metadata.file_type().is_symlink(),
            "{} must be a symlink, like Go's install produces",
            path.display()
        );
        let got_target = fs::read_link(&path).expect("symlink must be readable");
        assert_eq!(
            got_target,
            want_target,
            "{} points at the wrong tree; Go links the render dir",
            path.display()
        );
    }
}

/// Reads one `key=value` line out of a child's stdout.
fn field(stdout: &str, key: &str) -> String {
    let prefix = format!("{key}=");
    stdout
        .lines()
        .find_map(|line| line.strip_prefix(&prefix))
        .unwrap_or_else(|| panic!("child output has no {key}= line:\n{stdout}"))
        .trim()
        .to_string()
}

/// Builds the filesystem state a fixture default scenario describes, then runs
/// the resolution in a child and compares all three paths against Go.
#[test]
fn default_paths_match_the_go_oracle_for_every_resolution_branch() {
    let fixture = load_fixture();
    let cases = fixture
        .get("defaults")
        .expect("fixture has defaults")
        .as_array()
        .unwrap();
    assert_eq!(cases.len(), 7, "every branch of the Go resolution rule");

    for case in cases {
        let name = case.get("name").and_then(Value::as_str).unwrap();
        let tmp = tempfile::tempdir().expect("scenario parent");
        // The fixture's `$ROOT` is the generator's single global temp root, and
        // every scenario lived in `$ROOT/<name>/…`; reproduce both parts.
        let scenario_root = tmp.path().join(name);
        let root_text = tmp.path().to_string_lossy().into_owned();

        let home = scenario_root.join("home");
        fs::create_dir_all(&home).unwrap();

        let recorded_xdg = case
            .get("xdg_data_home")
            .and_then(Value::as_str)
            .expect("xdg field");
        let xdg = if recorded_xdg.is_empty() {
            None
        } else {
            Some(recorded_xdg.replacen("$ROOT", &root_text, 1))
        };

        // The base Go resolves against: an absolute XDG value, else HOME.
        let data_base = match xdg.as_deref() {
            Some(value) if Path::new(value).is_absolute() => PathBuf::from(value),
            _ => home.join(".local/share"),
        };
        if case.get("current_created").and_then(Value::as_bool) == Some(true) {
            fs::create_dir_all(data_base.join("symbrain").join("skills")).unwrap();
        }
        if case.get("legacy_created").and_then(Value::as_bool) == Some(true) {
            fs::create_dir_all(data_base.join("symskills")).unwrap();
        }

        let mut envs = vec![
            ("HOME".to_string(), home.to_string_lossy().into_owned()),
            (
                "USERPROFILE".to_string(),
                home.to_string_lossy().into_owned(),
            ),
        ];
        if let Some(value) = xdg {
            envs.push(("XDG_DATA_HOME".to_string(), value));
        }
        let stdout = run_child_case("child_resolves_defaults", &envs);

        let expected = |key: &str| -> String {
            case.get(key)
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("{name}: fixture has no {key}"))
                .replacen("$ROOT", &root_text, 1)
        };
        assert_eq!(
            PathBuf::from(field(&stdout, "library")),
            PathBuf::from(expected("library_dir")),
            "{name}"
        );
        assert_eq!(
            PathBuf::from(field(&stdout, "render")),
            PathBuf::from(expected("render_dir")),
            "{name}"
        );
        assert_eq!(
            PathBuf::from(field(&stdout, "base")),
            PathBuf::from(expected("base_dir")),
            "{name}"
        );
        assert_eq!(PathBuf::from(field(&stdout, "home")), home, "{name}");
    }
}

/// A competing current root under the wrong home must not outrank the legacy
/// root under the platform home when `XDG_DATA_HOME` is unset.
#[test]
fn conflicting_home_variables_use_the_go_platform_home() {
    let tmp = tempfile::tempdir().unwrap();
    let home = tmp.path().join("home");
    let profile = tmp.path().join("profile");
    let selected = if cfg!(windows) { &profile } else { &home };
    let other = if cfg!(windows) { &home } else { &profile };
    let legacy = selected.join(".local/share/symskills");
    fs::create_dir_all(&legacy).unwrap();
    fs::create_dir_all(other.join(".local/share/symbrain/skills")).unwrap();
    let stdout = run_child_case(
        "child_resolves_defaults",
        &[
            ("HOME".to_string(), home.to_string_lossy().into_owned()),
            (
                "USERPROFILE".to_string(),
                profile.to_string_lossy().into_owned(),
            ),
        ],
    );
    assert_eq!(
        PathBuf::from(field(&stdout, "library")),
        legacy.join("library")
    );
    assert_eq!(
        PathBuf::from(field(&stdout, "render")),
        legacy.join("rendered")
    );
    assert_eq!(PathBuf::from(field(&stdout, "base")), legacy.join("base"));
    assert_eq!(PathBuf::from(field(&stdout, "home")), selected.as_path());
}

/// Go's `TestRunBinaryPresenceChangesNothing`: a legacy `symskills` binary first
/// on `PATH` must not change the plan.
#[test]
fn a_legacy_symskills_binary_on_path_changes_nothing() {
    let fixture = load_fixture();
    let expected_case = fixture
        .get("cases")
        .and_then(Value::as_array)
        .unwrap()
        .iter()
        .find(|c| c.get("name").and_then(Value::as_str) == Some("binary_presence_changes_nothing"))
        .expect("fixture has the binary-presence case")
        .clone();

    let tmp = tempfile::tempdir().expect("scenario root");
    let bin = tmp.path().join("bin");
    fs::create_dir_all(&bin).unwrap();
    let fake = bin.join("symskills");
    fs::write(&fake, "#!/bin/sh\necho legacy\n").unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&fake, fs::Permissions::from_mode(0o755)).unwrap();
    }

    let inherited_path = std::env::var("PATH").unwrap_or_default();
    let envs = vec![
        (
            "RUNNER_CHILD_ROOT".to_string(),
            tmp.path().to_string_lossy().into_owned(),
        ),
        (
            "PATH".to_string(),
            format!("{}:{}", bin.to_string_lossy(), inherited_path),
        ),
    ];
    let stdout = run_child_case("child_runs_dry_run_with_legacy_binary", &envs);

    let expected_results = expected_case
        .get("results")
        .and_then(Value::as_array)
        .expect("expected results");
    let lines: Vec<&str> = stdout
        .lines()
        .filter(|line| line.starts_with("result="))
        .collect();
    assert_eq!(
        lines.len(),
        expected_results.len(),
        "child must report one result per target:\n{stdout}"
    );
    for (line, expected) in lines.iter().zip(expected_results.iter()) {
        let got = line.trim_start_matches("result=");
        let want = format!(
            "{}|{}|{}",
            expected.get("target").and_then(Value::as_str).unwrap(),
            expected.get("status").and_then(Value::as_str).unwrap(),
            expected
                .get("message")
                .and_then(Value::as_str)
                .unwrap_or("")
        );
        assert_eq!(got, want, "target/status/message triple");
    }
}

/// Child case: resolve the defaults under the parent's environment and print
/// the three paths and the harness home.
#[test]
#[ignore = "runs in a child process prepared by default_paths_match_the_go_oracle_for_every_resolution_branch"]
fn child_resolves_defaults() {
    let opts = symbrain_skills::runner::Options::default()
        .with_defaults()
        .expect("with_defaults must resolve under the child environment");
    println!("library={}", opts.library_dir);
    println!("render={}", opts.render_dir);
    println!("base={}", opts.base_dir);
    println!("home={}", opts.home_dir);
}

/// Child case: dry-run over claude and codex while a legacy binary sits first on
/// `PATH`, printing one `target|status|message` line per target.
#[test]
#[ignore = "runs in a child process prepared by a_legacy_symskills_binary_on_path_changes_nothing"]
fn child_runs_dry_run_with_legacy_binary() {
    use symbrain_skills::runner::{self, NoopContext, Options};

    let root = PathBuf::from(std::env::var("RUNNER_CHILD_ROOT").expect("RUNNER_CHILD_ROOT"));
    let skill_dir = root.join("library").join("demo");
    fs::create_dir_all(&skill_dir).unwrap();
    fs::write(
        skill_dir.join("SKILL.md"),
        "---\nname: demo\ndescription: test\n---\n\n# Demo\nBody.\n",
    )
    .unwrap();

    let opts = Options {
        library_dir: root.join("library").to_string_lossy().into(),
        render_dir: root.join("rendered").to_string_lossy().into(),
        base_dir: root.join("base").to_string_lossy().into(),
        home_dir: root.to_string_lossy().into(),
        ..Options::default()
    };
    let mut ctx = NoopContext;
    let results = runner::run(&mut ctx, &["claude".into(), "codex".into()], opts, true)
        .expect("dry-run must succeed");
    for result in results {
        println!(
            "result={}|{}|{}",
            result.target,
            result.status,
            result.message.as_deref().unwrap_or("")
        );
    }
}
