//! Known typed fields of the immutable Go memory config (dcddcef0/CoreKit v0.17.0).
//! Unknown keys are ignored; invalid known fields reset the entire CLI config.

#[derive(Clone, Copy)]
pub(super) enum Kind {
    String,
    Integer,
    Float,
    Bool,
    PointerBool,
    Strings,
    Map,
}

pub(super) const FIELDS: &[(&str, Kind)] = &[
    ("database.path", Kind::String),
    ("ollama.url", Kind::String),
    ("ollama.model", Kind::String),
    ("jwt.secret_path", Kind::String),
    ("jwt.secret", Kind::String),
    ("security.pii_enabled", Kind::PointerBool),
    ("security.trusted_proxies", Kind::Strings),
    ("security.require_profile", Kind::Bool),
    ("server.http_port", Kind::Integer),
    ("consolidation.enabled", Kind::Bool),
    ("consolidation.schedule", Kind::String),
    ("consolidation.idle_timeout", Kind::String),
    ("consolidation.timeout", Kind::String),
    ("consolidation.provider", Kind::String),
    ("consolidation.model", Kind::String),
    ("consolidation.url", Kind::String),
    ("ranking.relevance_weight", Kind::Float),
    ("ranking.recency_weight", Kind::Float),
    ("ranking.importance_weight", Kind::Float),
    ("ranking.access_reinforcement_weight", Kind::Float),
    ("ranking.recency_half_life", Kind::Float),
    ("ranking.access_half_life", Kind::Float),
    ("ranking.access_spacing_half_life", Kind::Float),
    ("ranking.spreading_weight", Kind::Float),
    ("context.token_budget", Kind::Integer),
    ("context.working_context_tokens", Kind::Integer),
    ("context.summary_tokens", Kind::Integer),
    ("context.retrieval_tokens", Kind::Integer),
    ("context.max_working_turns", Kind::Integer),
    ("degradation.enabled", Kind::Bool),
    ("degradation.full_tokens", Kind::Integer),
    ("degradation.summary_tokens", Kind::Integer),
    ("degradation.ref_tokens", Kind::Integer),
    ("degradation.summary_ratio", Kind::Float),
    ("delta_pack.enabled", Kind::Bool),
    ("delta_pack.max_snapshots", Kind::Integer),
    ("delta_pack.snapshot_on_token_pct", Kind::Integer),
    ("delta_pack.min_snapshot_interval_secs", Kind::Integer),
    ("profile_layer.enabled", Kind::Bool),
    ("profile_layer.max_static_len", Kind::Integer),
    ("profile_layer.max_dynamic_len", Kind::Integer),
    ("profile_layer.token_budget", Kind::Integer),
    ("session_context.enabled", Kind::Bool),
    ("session_context.max_sources", Kind::Integer),
    ("session_context.token_budget", Kind::Integer),
    ("session_context.max_expand_per_src", Kind::Integer),
    ("retention.session_ttl", Kind::String),
    ("retention.auto_purge_enabled", Kind::Bool),
    ("retention.audit_log_enabled", Kind::Bool),
    ("retention.audit_retention", Kind::String),
    ("retention.activity_segment_ttl", Kind::String),
    ("retention.activity_episode_ttl", Kind::String),
    ("query_log.max_entries", Kind::Integer),
    ("query_log.max_age", Kind::String),
    ("query_log.record_results", Kind::Bool),
    ("hybrid_search.enabled", Kind::Bool),
    ("hybrid_search.bm25_weight", Kind::Float),
    ("hybrid_search.vector_weight", Kind::Float),
    ("hybrid_search.mmr_enabled", Kind::Bool),
    ("hybrid_search.mmr_lambda", Kind::Float),
    ("hybrid_search.quantize_to_binary", Kind::Bool),
    ("hybrid_search.prefilter_enabled", Kind::Bool),
    ("hybrid_search.sparsemax_enabled", Kind::Bool),
    ("hybrid_search.per_arm_multiplier", Kind::Integer),
    ("search.min_score", Kind::Float),
    ("search.temporal_extraction_enabled", Kind::Bool),
    ("import.tools", Kind::Map),
    ("import.extract_on_import", Kind::Bool),
    ("working_memory.ttl", Kind::String),
    ("working_memory.max_items", Kind::Integer),
    ("working_memory.include_in_context", Kind::Bool),
    ("mcp.client_id", Kind::String),
    ("mcp.recall_receipts", Kind::Bool),
    ("memory.stage_writes_by_default", Kind::Bool),
    ("aging.enabled", Kind::Bool),
    ("aging.access_half_life_days", Kind::Float),
    ("aging.retire_below", Kind::Float),
    ("aging.access_boost_cap", Kind::Integer),
    ("conflict.enabled", Kind::Bool),
    ("conflict.contradiction_threshold", Kind::Float),
    ("conflict.near_dup_threshold", Kind::Float),
    ("conflict.max_candidates", Kind::Integer),
    ("conflict.llm_provider", Kind::String),
    ("conflict.llm_model", Kind::String),
    ("conflict.llm_url", Kind::String),
    ("prompt_mode", Kind::String),
];
