// Command generate-go-printable-table emits the Unicode printability table
// used to reproduce strconv.IsPrint in the Rust config formatter.
package main

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"strconv"
	"unicode"
)

type unicodeRange struct {
	first rune
	last  rune
}

func main() {
	output := flag.String("output", "rust/symbrain-core/src/go_printable.rs", "generated Rust output path")
	check := flag.Bool("check", false, "fail if the output is not up to date")
	flag.Parse()

	ranges := make([]unicodeRange, 0, 256)
	for codePoint := rune(0); codePoint <= 0x10ffff; codePoint++ {
		if codePoint >= 0xd800 && codePoint <= 0xdfff {
			continue
		}
		if !strconv.IsPrint(codePoint) {
			continue
		}
		if len(ranges) > 0 && ranges[len(ranges)-1].last+1 == codePoint {
			ranges[len(ranges)-1].last = codePoint
		} else {
			ranges = append(ranges, unicodeRange{first: codePoint, last: codePoint})
		}
	}

	content := "// @generated by scripts/generate-go-printable-table.go; do not edit.\n"
	content += fmt.Sprintf("// Source: %s, Unicode %s.\n\n", runtime.Version(), unicode.Version)
	content += "/// Unicode scalar ranges for Go strconv.IsPrint.\n"
	content += "pub(super) const PRINTABLE_RANGES: &[(u32, u32)] = &[\n"
	for _, r := range ranges {
		content += fmt.Sprintf("    (0x%04x, 0x%04x),\n", r.first, r.last)
	}
	content += "];\n\n"
	content += "pub(super) fn is_printable(ch: char) -> bool {\n"
	content += "    let code_point = ch as u32;\n"
	content += "    let mut low = 0;\n"
	content += "    let mut high = PRINTABLE_RANGES.len();\n"
	content += "    while low < high {\n"
	content += "        let middle = low + (high - low) / 2;\n"
	content += "        let (first, last) = PRINTABLE_RANGES[middle];\n"
	content += "        if code_point < first {\n"
	content += "            high = middle;\n"
	content += "        } else if code_point > last {\n"
	content += "            low = middle + 1;\n"
	content += "        } else {\n"
	content += "            return true;\n"
	content += "        }\n"
	content += "    }\n"
	content += "    false\n"
	content += "}\n"

	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", *output, err)
			os.Exit(1)
		}
		if string(existing) != content {
			fmt.Fprintf(os.Stderr, "%s is out of date; run go run scripts/generate-go-printable-table.go\n", *output)
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *output, err)
		os.Exit(1)
	}
}
