//! Differential test: the native SQLite layer against the frozen Go facts.
//!
//! `tests/fixtures/db_memory_oracle.json` is generated by
//! `scripts/db-memory-oracle`, which imports the production Go packages
//! (`internal/memory/config`, `internal/memory/db`), creates a real store and
//! reads the schema, the pragmas and the constraint behaviour back out of
//! SQLite. This module holds the native store to those same facts.
//!
//! It lives inside the crate on purpose: `busy_timeout` and `foreign_keys` are
//! connection-scoped, so they can only be observed the way the oracle observed
//! them — on the store's own connection.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use rusqlite::Connection;
use serde_json::Value;

use crate::model::Store;

fn fixture() -> Value {
    serde_json::from_str(include_str!("../tests/fixtures/db_memory_oracle.json"))
        .expect("db memory oracle fixture")
}

/// Opens a store in a private directory so parallel tests cannot collide.
fn open_store(tag: &str) -> (Store, PathBuf) {
    let directory = std::env::temp_dir().join(format!(
        "symbrain-db-oracle-{tag}-{}-{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    let _ = std::fs::remove_dir_all(&directory);
    std::fs::create_dir_all(&directory).expect("tempdir");
    let path = directory.join("memory.db");
    (Store::open(&path).expect("store"), path)
}

/// Runs `body` against the store's own connection.
fn with_conn<T>(store: &Store, body: impl FnOnce(&Connection) -> T) -> T {
    let guard = store.lock().expect("store lock");
    body(&guard)
}

fn table_names(conn: &Connection) -> BTreeSet<String> {
    let mut statement = conn
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'")
        .expect("prepare table names");
    let rows = statement
        .query_map([], |row| row.get::<_, String>(0))
        .expect("query table names");
    rows.map(|row| row.expect("table row")).collect()
}

/// `PRAGMA index_list(memories)` names, with `unique` derived exactly as
/// `scripts/db-memory-oracle` derives it: an index is unique iff its stored
/// SQL contains the bytes `UNIQUE`. The SQLite autoindex for a PRIMARY KEY
/// has empty stored SQL, so it reports `false` — matching the Go oracle.
fn index_facts(conn: &Connection) -> BTreeSet<(String, bool)> {
    let mut list = conn
        .prepare("PRAGMA index_list(memories)")
        .expect("prepare index list");
    let names: Vec<String> = list
        .query_map([], |row| row.get::<_, String>(1))
        .expect("query index names")
        .map(|row| row.expect("index name"))
        .collect();
    drop(list);
    names
        .into_iter()
        .map(|name| {
            let mut stmt = conn
                .prepare("SELECT sql FROM sqlite_master WHERE type='index' AND name=?")
                .expect("prepare index sql");
            let sql: Option<String> = stmt
                .query_row([&name], |row| row.get::<_, Option<String>>(0))
                .expect("query index sql");
            let unique = sql.is_some_and(|s| s.contains("UNIQUE"));
            (name, unique)
        })
        .collect()
}

/// `sqlite_master` facts for triggers and views: name plus stored SQL.
///
/// SQLite strips `IF NOT EXISTS` from the stored text, so the shipped DDL and
/// the native one are directly comparable; whitespace is collapsed because the
/// stored text keeps the author's indentation and the fixture's formatting is
/// not part of the contract.
fn statement_facts(conn: &Connection, kind: &str) -> BTreeMap<String, String> {
    let mut statement = conn
        .prepare(
            "SELECT name, sql FROM sqlite_master WHERE type = ? AND sql IS NOT NULL ORDER BY name",
        )
        .expect("prepare statement list");
    let rows = statement
        .query_map([kind], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })
        .expect("query statements");
    rows.map(|row| {
        let (name, sql) = row.expect("statement row");
        (name, collapse_whitespace(&sql))
    })
    .collect()
}

fn collapse_whitespace(sql: &str) -> String {
    sql.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// `PRAGMA table_info` facts, in declaration order.
fn column_facts(
    conn: &Connection,
    table: &str,
) -> Vec<(String, String, bool, Option<String>, i64)> {
    let mut statement = conn
        .prepare(&format!("PRAGMA table_info({table})"))
        .expect("prepare columns");
    let rows = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, i64>(3)? != 0,
                row.get::<_, Option<String>>(4)?,
                row.get::<_, i64>(5)?,
            ))
        })
        .expect("query columns");
    rows.map(|row| row.expect("column row")).collect()
}

fn pragma_i64(conn: &Connection, name: &str) -> i64 {
    conn.query_row(&format!("PRAGMA {name}"), [], |row| row.get(0))
        .expect("integer pragma")
}

fn pragma_text(conn: &Connection, name: &str) -> String {
    conn.query_row(&format!("PRAGMA {name}"), [], |row| row.get(0))
        .expect("text pragma")
}

fn expected_tables(fixture: &Value) -> BTreeSet<String> {
    fixture["schema"]["tables"]
        .as_array()
        .expect("tables array")
        .iter()
        .map(|table| table["name"].as_str().expect("table name").to_owned())
        .collect()
}

fn expected_indexes(fixture: &Value) -> BTreeSet<(String, bool)> {
    fixture["schema"]["indexes"]
        .as_array()
        .expect("indexes array")
        .iter()
        .map(|index| {
            (
                index["name"].as_str().expect("index name").to_owned(),
                index["unique"].as_bool().unwrap_or(false),
            )
        })
        .collect()
}

fn expected_columns(fixture: &Value) -> Vec<(String, String, bool, Option<String>, i64)> {
    fixture["schema"]["memories_columns"]
        .as_array()
        .expect("column array")
        .iter()
        .map(|column| {
            (
                column["name"].as_str().expect("column name").to_owned(),
                column["type"].as_str().expect("column type").to_owned(),
                column["not_null"].as_bool().unwrap_or(false),
                column["default_value"].as_str().map(str::to_owned),
                column["pk"].as_i64().unwrap_or(0),
            )
        })
        .collect()
}

#[test]
fn tables_match_the_go_schema() {
    let fixture = fixture();
    let (store, _path) = open_store("tables");
    let actual = with_conn(&store, table_names);
    let expected = expected_tables(&fixture);
    let missing: Vec<_> = expected.difference(&actual).cloned().collect();
    let extra: Vec<_> = actual.difference(&expected).cloned().collect();
    assert!(
        missing.is_empty() && extra.is_empty(),
        "table set diverges from Go: missing {missing:?}, extra {extra:?}"
    );
}

#[test]
fn memories_columns_match_the_go_schema() {
    let fixture = fixture();
    let (store, _path) = open_store("columns");
    let actual = with_conn(&store, |conn| column_facts(conn, "memories"));
    assert_eq!(
        actual,
        expected_columns(&fixture),
        "memories column facts diverge from Go"
    );
}

#[test]
fn indexes_match_the_go_schema() {
    let fixture = fixture();
    let (store, _path) = open_store("indexes");
    let actual = with_conn(&store, index_facts);
    let expected = expected_indexes(&fixture);
    let missing: Vec<_> = expected.difference(&actual).cloned().collect();
    let extra: Vec<_> = actual.difference(&expected).cloned().collect();
    assert!(
        missing.is_empty() && extra.is_empty(),
        "index set diverges from Go: missing {missing:?}, extra {extra:?}"
    );
}

#[test]
fn lock_pragmas_match_the_go_facts() {
    let fixture = fixture();
    let lock = &fixture["lock"];
    let (store, _path) = open_store("pragmas");
    let (busy_timeout, journal_mode, foreign_keys, secure_delete) = with_conn(&store, |conn| {
        (
            pragma_i64(conn, "busy_timeout"),
            pragma_text(conn, "journal_mode"),
            pragma_i64(conn, "foreign_keys"),
            pragma_i64(conn, "secure_delete"),
        )
    });
    assert_eq!(
        busy_timeout,
        lock["busy_timeout_ms"].as_i64().expect("busy_timeout_ms"),
        "busy_timeout diverges from Go"
    );
    assert_eq!(
        journal_mode.to_ascii_lowercase(),
        lock["journal_mode"]
            .as_str()
            .expect("journal_mode")
            .to_ascii_lowercase(),
        "journal_mode diverges from Go"
    );
    assert_eq!(
        foreign_keys,
        lock["foreign_keys"].as_i64().expect("foreign_keys"),
        "foreign_keys diverges from Go"
    );
    assert_eq!(
        secure_delete,
        lock["secure_delete"].as_i64().expect("secure_delete"),
        "secure_delete diverges from Go"
    );
}

/// The identifiers the Go error named, so a rejection can be compared without
/// depending on either driver's message formatting.
fn named_identifiers(message: &str) -> Vec<&str> {
    ["created_at", "updated_at", "nonexistent_table"]
        .into_iter()
        .filter(|name| message.contains(name))
        .collect()
}

#[test]
fn constraint_cases_are_rejected_like_go() {
    let fixture = fixture();
    let (store, _path) = open_store("constraints");
    for case in fixture["negative_cases"]
        .as_array()
        .expect("negative cases")
    {
        let name = case["name"].as_str().expect("case name");
        let sql = case["sql"].as_str().expect("case sql");
        if !case["rejected"].as_bool().unwrap_or(false) {
            // `legacy_schema_migrated` describes a Go migration over a legacy
            // database file, not a statement the native store replays here.
            continue;
        }
        let outcome = with_conn(&store, |conn| conn.execute_batch(sql));
        let error = outcome.expect_err(&format!("{name}: expected a rejection"));
        let expected_names = named_identifiers(case["error"].as_str().unwrap_or_default());
        let actual = error.to_string();
        for identifier in expected_names {
            assert!(
                actual.contains(identifier),
                "{name}: rejection {actual:?} does not name {identifier}"
            );
        }
    }
}

#[test]
fn ordering_cases_match_the_go_facts() {
    let fixture = fixture();
    let (store, _path) = open_store("ordering");
    for case in fixture["ordering_cases"]
        .as_array()
        .expect("ordering cases")
    {
        let name = case["name"].as_str().expect("case name");
        let seed = case["seed_sql"].as_str().expect("seed sql");
        let query = case["query_sql"].as_str().expect("query sql");
        let expected: Vec<String> = case["expected_ids"]
            .as_array()
            .expect("expected ids")
            .iter()
            .map(|id| id.as_str().expect("id").to_owned())
            .collect();
        assert!(
            !expected.is_empty(),
            "{name}: the fixture carries no expectation"
        );
        let actual = with_conn(&store, |conn| {
            conn.execute_batch(seed).expect("seed rows");
            let mut statement = conn.prepare(query).expect("prepare ordering query");
            let rows = statement
                .query_map([], |row| row.get::<_, String>(0))
                .expect("query ids");
            rows.map(|row| row.expect("id row"))
                .collect::<Vec<String>>()
        });
        assert_eq!(actual, expected, "{name}: ordering diverges from Go");
    }
}

/// A table can exist and still be dead: `memories_fts` without its
/// `memories_ai`/`_ad`/`_au` triggers never receives a row, and the table list
/// alone cannot show that. Triggers and views are compared by stored SQL
/// because neither has a PRAGMA to introspect.
#[test]
fn triggers_and_views_match_the_go_schema() {
    let fixture = fixture();
    let (store, _path) = open_store("triggers");
    for (section, kind) in [("triggers", "trigger"), ("views", "view")] {
        let expected: BTreeMap<String, String> = fixture["schema"][section]
            .as_array()
            .expect("fixture section")
            .iter()
            .map(|entry| {
                (
                    entry["name"].as_str().expect("name").to_owned(),
                    collapse_whitespace(entry["sql"].as_str().expect("sql")),
                )
            })
            .collect();
        let actual = with_conn(&store, |conn| statement_facts(conn, kind));
        assert_eq!(actual, expected, "{section} diverge from Go");
    }
}
